name: slurp-registry
version: 0.1.0.0
github: mboes/slurp-registry
license: PublicDomain
author: Mathieu Boespflug
maintainer: m@tweag.io
synopsis: Global registry of Haskell packages.
category: Web

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >= 1.2
- base >= 4.7 && < 5
- servant-server >= 0.11
- text

library:
  source-dirs: api
  exposed-modules:
  - Slurp.Registry.API
  dependencies:
  - modern-uri >= 0.1
  - time

executables:
  slurp-registry:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - bytestring >= 0.10
    - filepath
    - lens
    - optparse-generic
    - path
    - path-io
    - slurp-registry
    - typed-process
    - wai-logger
    - warp
    - warp-tls
