name: slurp-registry
version: 0.1.0.0
github: mboes/slurp-registry
license: PublicDomain
author: Mathieu Boespflug
maintainer: m@tweag.io
synopsis: Global registry of Haskell packages.
category: Web

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >= 1.2
- base >= 4.7 && < 5
- bytestring >= 0.10
- filepath
- lens
- modern-uri >= 0.1
- optparse-generic
- path
- path-io
- typed-process
- servant-server >= 0.11
- servant-swagger >= 1.1
- text
- time
- transformers
- wai
- warp
- warp-tls

library:
  source-dirs: api
  exposed-modules:
    - Slurp.Registry.API

executables:
  slurp-registry-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
      - slurp-registry
