version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/slurp-registry
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash
            nix-env -f nixpkgs.nix -iA stack
            mkdir -p ~/.stack
            echo 'nix: { enable: true }' > ~/.stack/config.yaml
      - run:
          name: Compute cache key
          command: |
            find . -name "*.cabal" -o -name "*.nix" -o -name "stack.yaml" -type f | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - slurp-registry-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}-1
            - slurp-registry-stack-dependencies-{{ arch }}-
      - run:
          name: Build dependencies
          command: |
            stack --no-terminal build --only-snapshot --prefetch --test --bench
            stack --no-terminal build hlint weeder
      - save_cache:
          key: slurp-registry-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}-1
          paths:
            - ~/.stack
      - run:
          name: Build project
          command: stack --no-terminal build --fast --pedantic --test --bench --no-run-tests --no-run-benchmarks
      - run:
          name: Check for weeds and lint
          command: |
            stack --no-terminal --no-nix-pure exec hlint api app
            stack --no-terminal --no-nix-pure exec weeder
      - run:
          name: Test
          command: stack --no-terminal test
